# Generated by Django 4.1.1 on 2022-09-27 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='dislike',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movie',
            name='like',
            field=models.IntegerField(default=0),
        ),
    ]
