# Generated by Django 4.1.1 on 2022-09-28 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_movie_dislike_movie_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='releaseYear',
            field=models.CharField(max_length=100),
        ),
    ]
