# Generated by Django 4.1.1 on 2022-09-29 19:58

from django.db import migrations, models
import movie.models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_alter_movie_releaseyear'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to=movie.models.upload_to),
        ),
    ]
